apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  secretName: argocd-sec
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: argocd.apiswagger.co.uk
  dnsNames:
  - argocd.apiswagger.co.uk
