apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # Replace this email address with your own.
    email: raja.nabeel@consultancyoutfit.co.uk
    # This is the Let's Encrypt production server URL
    server: https://acme-v02.api.letsencrypt.org/directory     
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: orcalo-production
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx




